version: '3.1'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=teapot-db
    ports:
      - 5050:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080