# Generated by Django 4.2.1 on 2023-05-11 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('card_number', django_cryptography.fields.encrypt(models.CharField())),
                ('expiry_date', django_cryptography.fields.encrypt(models.CharField())),
                ('card_holder', django_cryptography.fields.encrypt(models.CharField())),
                ('cvv', django_cryptography.fields.encrypt(models.CharField())),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
