# Generated by Django 4.2.1 on 2023-05-12 02:39

from django.db import migrations

def add_initial_categories(apps, schema_editor):
    Category = apps.get_model("category", "Category")

    categories = [
        "Apparel",
        "Electronics",
        "Home and Kitchen",
        "Beauty and Personal Care",
        "Books",
        "Pet Supplies",
        "Sports and Outdoors",
        "Grocery and Foods",
        "Toys and Games",
        "Others",
    ]

    for category in categories:
        Category.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_categories)
    ]
